# Generated by Django 5.0 on 2025-08-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_rename_contactmessage_contact_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="ContactMessage",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
