# Generated by Django 5.0 on 2025-08-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_contact_contactmessage_delete_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
