# Generated by Django 5.0 on 2025-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_contactmessage_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                choices=[
                    ("web-app", "Aplicación Web"),
                    ("mobile-app", "Aplicación Móvil"),
                    ("enterprise", "Sistema Empresarial"),
                    ("api", "API/Backend"),
                    ("consulting", "Consultoría Técnica"),
                    ("other", "Otro"),
                ],
                max_length=200,
            ),
        ),
    ]
