# Generated by Django 5.0 on 2025-08-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_contactmessage_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                choices=[
                    ("saas-app", "Desarrollo de Aplicaciones y Software SaaS"),
                    ("mobile-app", "Aplicación Móvil"),
                    ("enterprise", "Sistema Empresarial"),
                    ("api", "API/Backend"),
                    ("ai-architecture", "Arquitectura de Software con IA"),
                    ("other", "Otro"),
                ],
                max_length=200,
            ),
        ),
    ]
