# Generated by Django 4.2.26 on 2025-12-03 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_contactmessage_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título del artículo (SEO: 50-60 caracteres)",
                        max_length=200,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Resumen corto (SEO: 150-160 caracteres)",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenido completo del artículo (formato HTML)"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "featured_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Texto alternativo para SEO",
                        max_length=200,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO Title (50-60 caracteres)",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Meta description (150-160 caracteres)",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Palabras clave separadas por comas",
                        max_length=255,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(blank=True, help_text="URL canónica si aplica"),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Título para redes sociales",
                        max_length=100,
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True,
                        help_text="Descripción para redes sociales",
                        max_length=200,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="1200x630px",
                        null=True,
                        upload_to="blog/og/",
                    ),
                ),
                ("schema_type", models.CharField(default="Article", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "reading_time",
                    models.IntegerField(
                        default=5, help_text="Tiempo de lectura en minutos"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Tags separados por comas", max_length=255
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.blogcategory",
                    ),
                ),
                (
                    "related_posts",
                    models.ManyToManyField(blank=True, to="core.blogpost"),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="core_blogpo_publish_4753d4_idx"
                    ),
                    models.Index(fields=["slug"], name="core_blogpo_slug_36a1f7_idx"),
                    models.Index(
                        fields=["status"], name="core_blogpo_status_032da8_idx"
                    ),
                ],
            },
        ),
    ]
