# Generated by Django 4.2.26 on 2025-12-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_blogcategory_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_news",
            field=models.BooleanField(
                default=False, help_text="Marcar como noticia para Google News"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="news_keywords_extra",
            field=models.CharField(
                blank=True,
                help_text="Keywords específicas para Google News",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="news_location",
            field=models.CharField(
                blank=True,
                help_text="Ubicación geográfica de la noticia (ej: Bogotá, Colombia)",
                max_length=100,
            ),
        ),
    ]
