# Generated by Django 4.2.26 on 2025-12-02 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="budget_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="reference_urls",
            field=models.TextField(
                blank=True, help_text="URLs de referencia (una por línea)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Requisitos técnicos y funcionalidades"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="special_notes",
            field=models.TextField(
                blank=True, help_text="Notas y restricciones especiales"
            ),
        ),
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="project_attachments/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="Size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="clients.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
