# Generated by Django 5.0 on 2025-08-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="ProjectRequirement",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
